CREATE DATABASE IF NOT EXISTS ProHealth CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ProHealth;

CREATE TABLE IF NOT EXISTS AdminUsers (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  FullName VARCHAR(120) NOT NULL,
  Email VARCHAR(120) NOT NULL UNIQUE,
  PasswordHash VARCHAR(255) NOT NULL,
  Role VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Insurances (
  Id VARCHAR(30) NOT NULL PRIMARY KEY,
  Nombre VARCHAR(120) NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Appointments (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  PatientName VARCHAR(120) NOT NULL,
  Phone VARCHAR(50) NOT NULL,
  Email VARCHAR(180) NOT NULL,
  InsuranceId VARCHAR(30) NOT NULL,
  SlotDate DATETIME NOT NULL,
  Notes VARCHAR(500),
  Status VARCHAR(20) NOT NULL DEFAULT 'SOLICITADA',
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_Appointments_Insurances FOREIGN KEY (InsuranceId) REFERENCES Insurances (Id)
) ENGINE=InnoDB;

CREATE INDEX IX_Appointments_SlotDate ON Appointments (SlotDate);
